[default]
extend-ignore-identifiers-re = [
    ".*_PER_BLOCK_OPTIN"
]

[default.extend-identifiers]
NervanaSystems = "NervanaSystems"

[type.svg]
extend-glob = ["*.svg"]
check-file = false

[type.bib]
extend-glob = ["*.bib"]
check-file = false
